name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out the code"
        uses: actions/checkout@master
        with:
            path: ./countgizmo.github.io
      - name: "Clone monologue"
        uses: actions/checkout@master
        with:
            repository: countgizmo/monologue
            path: ./monologue
      - name: "Install Clojure"
        uses: DeLaGuardo/setup-clojure@master
        with:
            cli: latest
      - name: "Generate the monologue site"
        run: |
            cd ./monologue
            clojure -m monologue.core generate -t ../countgizmo.github.io/thoughts -s ../countgizmo.github.io/docs
      - name: "Commit the updated site"
        run: |
            cd ./countgizmo.github.io
            git config user.email "count.gizmo@gmail.com"
            git config user.name "countgizmo"
            if [ -n "$(git status --porcelain)" ]; then
                git add .
                git commit -m "[CI] Generate site"
                git push
            else
                echo "Nothing to commit, bye-bye!"
            fi
